socialmedia/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('settings/',views.settings,name='settings'),
    path('upload/',views.upload,name='upload'),
    path('delete/<int:post_id>/',views.delete_post,name='delete'),
    path('like/',views.like_post,name='like'),
    path('profile/<str:pk>/',views.profile,name='profile'),
    path('follow/',views.follow,name='follow'),
    path('search/',views.search,name='search'),
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user/',include('user.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialmedia/user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

socialmedia/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>sign in</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body class="bg-gray-100">


    <div id="wrapper" class="flex flex-col justify-between h-screen">

        <!-- header-->
        <div class="bg-white py-4 shadow dark:bg-gray-800">
            <div class="max-w-6xl mx-auto">


                <div class="flex items-center lg:justify-between justify-around">

                    <a href="trending.html">
                       <b><h1 style="font-size: 1.5rem;">Friendzzz</h1></b>
                    </a>

                    <div class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm">
                        
                        <a href="{% url 'user:signup' %}" class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white">Register</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Content-->
        <div>
            <div class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                <h1 class="lg:text-3xl text-xl font-semibold  mb-6"> Login</h1>
                <form action="" method='POST'>
                    {% csrf_token %}

                    {% if messages %}
                    {% for message in messages  %}
                    <div class="error-div">
                        <h2 class="email-error">
                            {{message}}
                        </h2>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <input autofocus type="text" name='username' placeholder="Username" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input type="password" name='password' placeholder="***********" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <button type="submit" class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full">Login</button>
                    <div class="text-center mt-5 space-x-2">
                        <p class="text-base"> Not registered? <a href="{% url 'user:signup' %}" class=""> Create a account </a></p>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Footer -->

        <div class="lg:mb-5 py-3 uk-link-reset">
            <div class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3">
                <div class="flex space-x-2 text-gray-700 uppercase">
                    <a href="#"> About</a>
                    <a href="#"> Help</a>
                    <a href="#"> Terms</a>
                    <a href="#"> Privacy</a>
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


</body>


</html>

socialmedia/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Profile - {{user_profile.user}}</title>
   <!-- <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> -->
    
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	
	</div>
	
	<section>
			<div class="feature-photo">
				<figure><img src="{% static 'images/resources/timeline-1.jpg' %}" alt=""></figure>
				<form action="{% url 'home:follow' %}" method="POST">
					{% csrf_token %}
					<div class="add-btn">
					<span style="color: white; font-size: 27px; margin-right: 520px;"><b><u><a href="/">Home</a></u></b></span>
					{% if post_length == 1 %}
					<span style="color: white; font-size: 27px;"><b>1 Post</b></span>
					{% elif post_length == 0 %}
					<span style="color: white; font-size: 27px;"><b>0 Post</b></span>
					{% else %}
					<span style="color: white; font-size: 27px;"><b>{{post_length}} Posts</b></span>
					{% endif %}
					<input type="hidden" name="follower" value="{{user.username}}">
					<input type="hidden" name="following" value="{{user_profile.user}}">	
					{% if user_follower == 1 %}
					<span style="color: white; font-size: 27px;"><b>{{user_follower}} follower</b></span>
					{% elif user_follower == 0 %}
					<span style="color: white; font-size: 27px;"><b>{{user_follower}} follower</b></span>
					{% else %}
					<span style="color: white; font-size: 27px;"><b>{{user_follower}} followers</b></span>
					{% endif %}
					<span style="color: white; font-size: 27px;"><b>{{user_following}} following</b></span>
					{% if user_object.username == user.username %}
					<a href="{% url 'home:settings' %}"  data-ripple="">Account settings</button></a>
					{% else %}
					<a  data-ripple=""><button type="submit" style="background-color: #ffc0cb; border: #ffc0cb;">{{button}}</button></a>
					{% endif %}
					</div>	
				</form>
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									<img src={{user_profile.profile_image.url}} style="height: 250px; width: 100%;" alt="">
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
									  <h5 style="color: black;white-space: nowrap; width: 110px; font-size: 27px;"><b>@{{user_profile.user}}</b><!--<i class="fa fa-check-circle" style="color: #48dbfb;" aria-hidden="true"></i>--></h5>
									  <!--<span>Group Admin</span>-->
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->
		<section>
			<div class="bio">
				{{user_profile.bio}}
			</div>
		</section>
		
	<section>
		<div class="gap gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row" id="page-contents">
							<div class="col-lg-3">
								<aside class="sidebar static">
									
									
									
								</aside>
							</div><!-- sidebar -->
							









							{% comment %} <div class="col-lg-6">
								<div class="central-meta">
									<ul class="photos">
				

										
									</ul>
									<!--<div class="lodmore"><button class="btn-view btn-load-more"></button></div>-->
								</div><!-- photos -->
							</div><!-- centerl meta --> {% endcomment %}
							<div class="container">
								<div class="row">
									{% for post in  user_post  %}
									<div class="col-md-4">
											<div class="card" style="width: 18rem;">
												<a class="strip" href={{post.post_image.url}} title="" data-strip-group="mygroup" data-strip-group-options="loop: false">
												<img src={{post.post_image.url}} style="height: 250px; width: 300px;" alt=""></a>
												<div class="card-body">
												  <h5 class="card-title">{{post.title}}</h5>
												  {% if post.post_like == 1 or post.post_like == 0 %}
												  liked by {{post.post_like}} person
													{% else %}
													liked by {{post.post_like}} persons
												  {% endif %}
												</div>
												{% if user.is_authenticated %}
												{% if post.user == request.user.username %}
													
													<a href="{% url 'home:delete' post.id %}" class="flex items-center px-3 py-2 text-red-500 hover:bg-red-100 hover:text-red-500 rounded-md ">
														<button style="background-color: #ffc0cb; border: #ffc0cb;">Delete</button>
													</a>   
												{% endif %}
												{% endif %}
											  </div>	
										</div>
										{% endfor %}
									</div>
								</div>
							</div>
							{% comment %} <div class="card">
								<div class="card-body">
									{% for post in user_post  %}
							
									<div class="card">
										<li>
											
										</li>
									</div>

									{% endfor %}
								</div> {% endcomment %}
							<div class="col-lg-3">
								<aside class="sidebar static">
									
								</aside>
							</div><!-- sidebar -->
						</div>	
					</div>
				</div>
			</div>
		</div>	
	</section>

	
	
	<script data-cfasync="false" src="{% static '../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
	<script src="{% static 'js/main.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>	


</html>

socialmedia/templates/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="favicon.png" rel="icon" type="image/png">
    <title>Search</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
            <form action="{% url 'home:search' %}" method="POST">
            {% csrf_token %}
            <header style="margin-top: -23px;">
                <div class="header_inner">
                    <div class="left-side">
                        <!-- Logo -->
                        <div id="logo" class=" uk-hidden@s">
                            <a href="/">
                                <!-- <b><h1 style="text-transform: uppercase;">Social Book</h1></b> -->
                            </a>
                        </div>

                        <!--<div class="triger" uk-toggle="target: #wrapper ; cls: sidebar-active">
                            <i class="uil-bars"></i>
                        </div>-->

                        <!-- <div class="header_search"> -->
                            
                                <input type="text" name="username" placeholder="Search for username..">&nbsp; &nbsp;
                                <button type="submit"><i class="fa fa-search fa-1x"></i></button>
                            
                            <!-- <div class="icon-search">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                </svg>
                            </div> -->
                        <!-- </div> -->

                    </div>
                    <div class="right-side lg:pr-4">
                        <!-- welcome user -->
                        <a href="#" class="">
                            Welcome <b name="" class="">{{user.username}}&nbsp; &nbsp; &nbsp;</b>
                        </a>
                        

                        <!-- profile -->

                        <a href="#">
                            <img src="{{ user_profile.profile_image.url }}" class="header-avatar" alt="">
                        </a>
                        <div uk-drop="mode: click;offset:9" class="header_dropdown profile_dropdown border-t">
                            <ul>
                                <li><a href="/settings"> Account setting </a> </li>
                                <!-- <li><a href="explore.html">explore </a> </li> -->
                                <li><a href="/logout"> Log Out</a></li>
                            </ul>
                        </div>

                    </div>
                </div>
            </header>
            </form>
            
            <div style="margin-left: 250px; margin-right: 250px;">
                
                <style>
                body{margin-top:20px;
                background-color: #eee;
                }

                .search-result-categories>li>a {
                    color: #b6b6b6;
                    font-weight: 400
                }

                .search-result-categories>li>a:hover {
                    background-color: #ddd;
                    color: #555
                }

                .search-result-categories>li>a>.glyphicon {
                    margin-right: 5px
                }

                .search-result-categories>li>a>.badge {
                    float: right
                }

                .search-results-count {
                    margin-top: 10px
                }

                .search-result-item {
                    padding: 20px;
                    background-color: #fff;
                    border-radius: 4px
                }

                .search-result-item:after,
                .search-result-item:before {
                    content: " ";
                    display: table
                }

                .search-result-item:after {
                    clear: both
                }

                .search-result-item .image-link {
                    display: block;
                    overflow: hidden;
                    border-top-left-radius: 4px;
                    border-bottom-left-radius: 4px
                }

                @media (min-width:768px) {
                    .search-result-item .image-link {
                        display: inline-block;
                        margin: -20px 0 -20px -20px;
                        float: left;
                        width: 200px
                    }
                }

                @media (max-width:767px) {
                    .search-result-item .image-link {
                        max-height: 200px
                    }
                }

                .search-result-item .image {
                    max-width: 100%
                }

                .search-result-item .info {
                    margin-top: 2px;
                    font-size: 12px;
                    color: #999
                }

                .search-result-item .description {
                    font-size: 13px
                }

                .search-result-item+.search-result-item {
                    margin-top: 20px
                }

                @media (min-width:768px) {
                    .search-result-item-body {
                        margin-left: 200px
                    }
                }

                .search-result-item-heading {
                    font-weight: 400
                }

                .search-result-item-heading>a {
                    color: #555
                }

                @media (min-width:768px) {
                    .search-result-item-heading {
                        margin: 0
                    }
                }
                </style>

                <div class="container">
                <div class="row ng-scope">
                    <div class="col-md-3 col-md-push-9">
                        
                        <h4>Results For <span class="fw-semi-bold"><b>{{username}}</b></span></h4>
                        <br>

                    </div>
                    <div class="col-md-9 col-md-pull-3">
                        <!-- <p class="search-results-count">About 94 700 000 (0.39 sec.) results</p> -->
                        
                        {% for users in username_profile_list %}
                        <section class="search-result-item">
                            <a class="image-link" href="/profile/{{users.user}}"><img class="image" width=80% src="{{users.profile_image.url}}">
                            </a>
                            <div class="search-result-item-body">
                                <div class="row">
                                    <div class="col-sm-9">
                                        <h4 class="search-result-item-heading"><a href="/profile/{{users.user}}"><b>@{{users.user}}</b></a></h4>
                                        <p class="info">{{users.location}}</p>
                                        <p class="description">{{users.bio}}</p>
                                    </div>
                                    <!-- <div class="col-sm-3 text-align-center">
                                        <p class="value3 mt-sm">$9, 700</p>
                                        <p class="fs-mini text-muted">PER WEEK</p><a class="btn btn-primary btn-info btn-sm" href="#">Learn More</a>
                                    </div> -->
                                </div>
                            </div>
                        </section>
                        {% endfor %}

                        <!-- <div class="text-align-center">
                            <ul class="pagination pagination-sm">
                                <li class="disabled"><a href="#">Prev</a>
                                </li>
                                <li class="active"><a href="#">1</a>
                                </li>
                                <li><a href="#">2</a>
                                </li>
                                <li><a href="#">3</a>
                                </li>
                                <li><a href="#">4</a>
                                </li>
                                <li><a href="#">5</a>
                                </li>
                                <li><a href="#">Next</a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
                </div>
            </div>

        </div>

    </div>








 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>
</body>


</html>

socialmedia/templates/setting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>Settings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body>


       

          

            <div class="container m-auto"> 

                <h1 class="text-2xl leading-none text-gray-900 tracking-tight mt-3"><a href="{% url 'home:index' %}">Home</a>/Account Setting for <b>@{{user.username}}</b></h1>
                {% comment %} <ul class="mt-5 -mr-3 flex-nowrap lg:overflow-hidden overflow-x-scroll uk-tab">
                    <li class="uk-active"><a href="#">General</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Notification</a></li>
                    <li><a href="#">Social links</a></li>
                    <li><a href="#">Billing</a></li>
                    <li><a href="#">Security</a></li>
                </ul> {% endcomment %}
                <br>
                <hr>
                <div class="grid lg:grid-cols-3 mt-12 gap-8">
                    <div>
                        <h3 class="text-xl mb-2"> General</h3>
                        <p></p>
                    </div>
                    <div class="bg-white rounded-md lg:shadow-lg shadow col-span-2">

                        <form action="" method='POST' enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                                <div class="col-span-2">
                                    <label for=""> Profile Image</label>
                                    <img width="100px" src="{{user_profile.profile_image.url}}" alt="{{user.username}}">
                                    <input name='image'  type="file" placeholder="Location" class="shadow-none bg-gray-100">
                                </div>
                                <div class="col-span-2">
                                    <label for="bio">Bio</label>  
                                    <textarea  name="bio" rows="3"  class="shadow-none bg-gray-100">{{user_profile.bio}}</textarea>
                                </div> 
                                <div class="col-span-2">
                                    <label for=""> Location</label>
                                    <input name='location' value='{{user_profile.location}}' type="text" placeholder="Location" class="shadow-none bg-gray-100">
                                </div>
                           </div> 
        
                           <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                               <a href="{% url 'home:index' %}"><button class="p-2 px-4 rounded bg-gray-50 text-red-500"> Cancel </button></a>
                               <button type="submit" class="button bg-blue-700"> Save </button>
                           </div>
                        </form>
    
                    </div>
                    </div>
    
                    </div>
                    <br>

                </div>

            </div>
            
        </div>

    </div>


    

 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>
</body>

</html>

socialmedia/templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>sign in</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body class="bg-gray-100">


    <div id="wrapper" class="flex flex-col justify-between h-screen">

        <!-- header-->
        <div class="bg-white py-4 shadow dark:bg-gray-800">
            <div class="max-w-6xl mx-auto">


                <div class="flex items-center lg:justify-between justify-around">

                    <a href="trending.html">
                       <b><h1 style="font-size: 1.5rem;">Socol</h1></b>
                    </a>

                    <div class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm">
                        
                        <a href="signup.html" class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white">Register</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Content-->
        <div>
            <div class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                <h1 class="lg:text-3xl text-xl font-semibold  mb-6"> Log in</h1>
                <form action="index.html">
                    <input type="text" placeholder="Username" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input type="text" placeholder="***********" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <div class="flex justify-between my-4">
                        <div class="checkbox">
                            <input type="checkbox" id="chekcbox1" checked>
                            <label for="chekcbox1"><span class="checkbox-icon"></span>Remember Me</label>
                        </div>
                        <a href="#"> Forgot Your Password? </a>
                    </div>
                    <button type="submit" class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full">Login</button>
                    <div class="text-center mt-5 space-x-2">
                        <p class="text-base"> Not registered? <a href="form-register.html" class=""> Create a account </a></p>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Footer -->

        <div class="lg:mb-5 py-3 uk-link-reset">
            <div class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3">
                <div class="flex space-x-2 text-gray-700 uppercase">
                    <a href="#"> About</a>
                    <a href="#"> Help</a>
                    <a href="#"> Terms</a>
                    <a href="#"> Privacy</a>
                </div>
                <p class="capitalize"> © copyright 2020 by socol</p>
            </div>
        </div>

    </div>


    <!--<script>
        
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);
    
    
        (function (window, document, undefined) {
    
            'use strict';
    
            // Feature test
            if (!('localStorage' in window)) return;
    
            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;
    
            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);
    
        })(window, document);
    </script>-->

    <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


</body>


</html>